services:
  # Servicio para la base de datos MySQL
  db:
    image: mysql:8.0  # Imagen de MySQL
    container_name: mysql_db_net  # Nombre del contenedor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: db
      MYSQL_USER: clinton
      MYSQL_PASSWORD: admin1234
    ports:
      - "3320:3306"  # Expone el puerto 3306
    volumes:
      - db_data:/var/lib/mysql  # Volumen persistente para la base de datos

volumes:
  db_data:  # Volumen para la persistencia de datos de MySQL